### ISSUE TITLE
Project bundles feature request

### ISSUE THREAD

**Issue by hewgreen** [HumanCellAtlas/dcp-diag#1]
When I provide a uuid it would be helpful if the tool could look into the nested submissions and pull out bundles if requested. Right now I have to run this as two commands.

This to get the submission id:
`dcpdig -d staging @ingest project_uuid=08e7b6ba-5825-47e9-be2d-7978533c5f8c --show submissions`

Then this to get the bundles:
`dcpdig -d staging @ingest submission_id=5bc598756b6f760006536b91 --show bundles > bundles_08e7b6ba-5825-47e9-be2d-7978533c5f8c.txt`

I like to be able to run:
`dcpdig -d staging @ingest project_uuid=08e7b6ba-5825-47e9-be2d-7978533c5f8c --show bundles`

**Comment by sampierson** [comment]
Hew and I agreed that the downloading bundles belongs in the hca cli.
I have however updated `dcpdig` so that you can start with a project and get submission and bundles in one shot:
```
pip install dcp-diag==0.11.0
dcpdig -d integration @ingest project_uuid=accf7a75-82b4-49ed-b6ef-07168ba0c072 --show submissions,bundles
Using deployment integration
Project 5c018921f8c91f000747a78a
    uuid=accf7a75-82b4-49ed-b6ef-07168ba0c072
    short_name=integration/10x/2018-11-30T19:01:52Z
	SubmissionEnvelope 5c018920f8c91f000747a787
	    uuid=8d9f5078-4127-4e3c-826c-9989dab25350
	    status=Complete
		Bundles:
		    b562972d-ae58-4a6c-a6a6-2097a61d1331
```
